### ISSUE TITLE
Task list 

### ISSUE THREAD

**Issue by d1by4** [d1by4/kodya_coffee#6]
- [ ] Buat halaman tentang
- [ ] Buat halaman menu
- [ ] Buat halaman detail menu
